//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public Nullable<int> EMPSEQ { get; set; }
        public string EMPCODE { get; set; }
        public string EMPTNAME { get; set; }
        public string EMPFNAME { get; set; }
        public string EMPLNAME { get; set; }
        public string EMPSEX { get; set; }
        public string DEPTCOD { get; set; }
        public string EMPPOSI { get; set; }
        public string EMPLEV { get; set; }
        public string EMPTYP { get; set; }
        public string EMPID { get; set; }
        public Nullable<System.DateTime> EMPSTRT { get; set; }
        public Nullable<System.DateTime> EMPBRTH { get; set; }
        public Nullable<int> EMPAGE { get; set; }
        public string EMPSTT { get; set; }
    }
}
